import { type NextPage } from 'next';
import Head from 'next/head';
import useAuth from '../lib/hooks/useAuth';
import { Button } from 'flowbite-react';
import { useRouter } from 'next/router';
import Link from 'next/link';
import CommonLayout from '../components/layouts/common.layout';

const Home: NextPage = () => {
	const { isAuthenticated, user } = useAuth();
	const router = useRouter();

	if (isAuthenticated) router.push('/app');

	return (
		<>
			<Head>
				<title>Ignosi - Home</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<CommonLayout>
				<div className="flex h-full flex-col items-start justify-center gap-6 px-14 py-52">
					{/* <p className="text-8xl">Ignosi</p> */}
					<div>
						{/* <p className="text-5xl">Your online education solution. </p> */}
						<p className="text-5xl">Creating a simple, efficient, and</p>
						<p className="text-5xl">secure learning environment.</p>
					</div>
					<Link href="/auth" className="rounded-md bg-blue-700 py-2 px-6 text-white hover:bg-blue-800">
						Join Ignosi
					</Link>
				</div>
			</CommonLayout>
		</>
	);
};

export default Home;
